Repository yanolja-finalproject/Backend, pull requests merged in 2024-01, with the labels that each got.

#32 [Feature] 회원가입, 탈퇴, 복구 기능 구현
  src/docs/asciidoc/user/user-api.adoc
  src/main/java/com/yanolja_final/domain/auth/controller/AuthController.java
  src/main/java/com/yanolja_final/domain/user/controller/EmailController.java
  src/main/java/com/yanolja_final/domain/user/controller/UserController.java
  src/main/java/com/yanolja_final/domain/user/controller/request/SignUpRequest.java
  src/main/java/com/yanolja_final/domain/user/controller/response/SignUpResponse.java
  src/main/java/com/yanolja_final/domain/user/dto/request/CreateUserRequest.java
  src/main/java/com/yanolja_final/domain/user/dto/request/EmailRequest.java
  src/main/java/com/yanolja_final/domain/user/dto/response/CreateUserResponse.java
  src/main/java/com/yanolja_final/domain/user/entity/User.java
  src/main/java/com/yanolja_final/domain/user/exception/PhoneNumberAlreadyRegisteredException.java
  src/main/java/com/yanolja_final/domain/user/facade/UserFacade.java
  src/main/java/com/yanolja_final/domain/user/repository/UserRepository.java
  src/main/java/com/yanolja_final/domain/user/service/ScheduledTasks.java
  src/main/java/com/yanolja_final/domain/user/service/UserService.java
  src/main/java/com/yanolja_final/global/config/security/SecurityConfig.java
  src/main/java/com/yanolja_final/global/exception/ErrorCode.java
  src/main/java/com/yanolja_final/global/util/ResponseDTO.java
  src/test/java/com/yanolja_final/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/yanolja_final/domain/user/controller/EmailControllerTest.java
  src/test/java/com/yanolja_final/domain/user/controller/UserControllerTest.java
  src/test/java/com/yanolja_final/domain/user/service/UserServiceTest.java
  src/test/java/com/yanolja_final/testutils/ControllerTestFixtureFactory.java
Labels: 🛠️feature, 🚧refactoring

#33 [Chore] ERD기반 entity클래스 파일 생성
  .env.sample
  src/main/java/com/yanolja_final/domain/advertisement/entity/Advertisement.java
  src/main/java/com/yanolja_final/domain/advertisement/entity/AdvertisementImage.java
  src/main/java/com/yanolja_final/domain/faq/entity/Faq.java
  src/main/java/com/yanolja_final/domain/notice/entity/Notice.java
  src/main/java/com/yanolja_final/domain/order/entity/Order.java
  src/main/java/com/yanolja_final/domain/packages/entity/Hashtag.java
  src/main/java/com/yanolja_final/domain/packages/entity/Package.java
  src/main/java/com/yanolja_final/domain/packages/entity/PackageAvailableDate.java
  src/main/java/com/yanolja_final/domain/packages/entity/PackageImage.java
  src/main/java/com/yanolja_final/domain/poll/entity/Poll.java
  src/main/java/com/yanolja_final/domain/poll/entity/PollAnswer.java
  src/main/java/com/yanolja_final/domain/poll/entity/PollQuestion.java
  src/main/java/com/yanolja_final/domain/review/entity/Review.java
  src/main/java/com/yanolja_final/domain/theme/entity/Theme.java
  src/main/java/com/yanolja_final/domain/user/entity/User.java
  src/main/java/com/yanolja_final/domain/user/entity/UserImage.java
  src/main/java/com/yanolja_final/domain/wish/entity/Wish.java
Labels: ❓question

#77 [Feature] 찜 등록, 삭제, 조회 구현
  src/main/java/com/yanolja_final/domain/packages/exception/PackageNotFoundException.java
  src/main/java/com/yanolja_final/domain/packages/repository/PackageRepository.java
  src/main/java/com/yanolja_final/domain/packages/service/PackageService.java
  src/main/java/com/yanolja_final/domain/user/service/UserService.java
  src/main/java/com/yanolja_final/domain/wish/controller/WishController.java
  src/main/java/com/yanolja_final/domain/wish/dto/request/WishRequest.java
  src/main/java/com/yanolja_final/domain/wish/dto/response/WishListResponse.java
  src/main/java/com/yanolja_final/domain/wish/entity/Wish.java
  src/main/java/com/yanolja_final/domain/wish/exception/WishNotFoundException.java
  src/main/java/com/yanolja_final/domain/wish/facade/WishFacade.java
  src/main/java/com/yanolja_final/domain/wish/repository/WishRepository.java
  src/main/java/com/yanolja_final/domain/wish/service/WishService.java
  src/main/java/com/yanolja_final/global/exception/ErrorCode.java
  src/main/java/com/yanolja_final/global/util/PaginationUtils.java
  src/main/resources/application.yml
Labels: 🛠️feature

#81 [Feature] 공지사항 글 작성 API
  src/main/java/com/yanolja_final/domain/notice/controller/NoticeController.java
  src/main/java/com/yanolja_final/domain/notice/dto/request/RegisterNoticeRequest.java
  src/main/java/com/yanolja_final/domain/notice/dto/response/RegisterNoticeResponse.java
  src/main/java/com/yanolja_final/domain/notice/entity/Notice.java
  src/main/java/com/yanolja_final/domain/notice/facade/NoticeFacade.java
  src/main/java/com/yanolja_final/domain/notice/repository/NoticeRepository.java
  src/main/java/com/yanolja_final/domain/notice/service/NoticeService.java
Labels: 🛠️feature

#84 [Refactor] 회원가입 리팩토링 및 닉네임 랜덤생성 로직 추가
  src/main/java/com/yanolja_final/domain/user/dto/request/CreateUserRequest.java
  src/main/java/com/yanolja_final/domain/user/dto/response/CreateUserResponse.java
  src/main/java/com/yanolja_final/domain/user/entity/User.java
  src/main/java/com/yanolja_final/domain/user/entity/UserImage.java
  src/main/java/com/yanolja_final/domain/user/service/UserService.java
  src/test/java/com/yanolja_final/domain/user/controller/UserControllerTest.java
  src/test/java/com/yanolja_final/domain/user/service/UserServiceTest.java
  src/test/java/com/yanolja_final/testutils/ControllerTestFixtureFactory.java
Labels: 🛠️feature, 🚧refactoring

#87 [Feature] 찬반 토론 결과 % 기능 구현
  src/main/java/com/yanolja_final/domain/poll/controller/request/PollAnswerRequest.java
  src/main/java/com/yanolja_final/domain/poll/controller/response/VotedResponse.java
  src/main/java/com/yanolja_final/domain/poll/dto/PollResultDTO.java
  src/main/java/com/yanolja_final/domain/poll/entity/Poll.java
  src/main/java/com/yanolja_final/domain/poll/exception/InvalidOptionException.java
  src/main/java/com/yanolja_final/domain/poll/service/PollService.java
  src/main/java/com/yanolja_final/global/exception/ErrorCode.java
  src/main/resources/data.sql
Labels: 🛠️feature

#88 [Feature] GET /v1/notices 공지사항 글 목록#61
  src/main/java/com/yanolja_final/domain/notice/controller/NoticeController.java
  src/main/java/com/yanolja_final/domain/notice/dto/response/NoticeListResponse.java
  src/main/java/com/yanolja_final/domain/notice/dto/response/RegisterNoticeResponse.java
  src/main/java/com/yanolja_final/domain/notice/entity/Notice.java
  src/main/java/com/yanolja_final/domain/notice/facade/NoticeFacade.java
  src/main/java/com/yanolja_final/domain/notice/service/NoticeService.java
Labels: 🛠️feature

#100 [Refactor] JPA Entity 변경으로 인한 API 테스트 및 수정
  src/main/java/com/yanolja_final/domain/wish/dto/response/WishListResponse.java
Labels: 👨🏻‍🔧fix, 🚧refactoring

#101 [Feature] 패키지 별 리뷰 조회 구현
  src/main/java/com/yanolja_final/domain/review/controller/ReviewController.java
  src/main/java/com/yanolja_final/domain/review/dto/response/ReviewSummaryResponse.java
  src/main/java/com/yanolja_final/domain/review/facade/ReviewFacade.java
  src/main/java/com/yanolja_final/domain/review/repository/ReviewRepository.java
  src/main/java/com/yanolja_final/domain/review/service/ReviewService.java
  src/main/java/com/yanolja_final/global/config/security/SecurityConfig.java
Labels: 🛠️feature

#103 [Feature] POST /v1/faq 자주 묻는 질문 글 작성#74
  src/main/java/com/yanolja_final/domain/faq/controller/FaqController.java
  src/main/java/com/yanolja_final/domain/faq/dto/request/RegisterFaqRequest.java
  src/main/java/com/yanolja_final/domain/faq/dto/response/FaqResponse.java
  src/main/java/com/yanolja_final/domain/faq/entity/Faq.java
  src/main/java/com/yanolja_final/domain/faq/facade/FaqFacade.java
  src/main/java/com/yanolja_final/domain/faq/repository/FaqRepository.java
  src/main/java/com/yanolja_final/domain/faq/service/FaqService.java
Labels: 🛠️feature

#114 [Chore] 무중단 자동 배포 구성
  .github/workflows/cd.yml
  build.gradle
  src/main/java/com/yanolja_final/domain/auth/controller/AuthController.java
  src/main/java/com/yanolja_final/domain/user/controller/UserController.java
  src/main/java/com/yanolja_final/global/common/CookieUtils.java
  src/main/java/com/yanolja_final/global/config/security/SecurityConfig.java
  src/main/java/com/yanolja_final/global/config/security/jwt/JwtFilter.java
  src/main/java/com/yanolja_final/global/deploy/DeployController.java
  src/main/resources/application.yml
Labels: 🛠️feature

#111 Feature/98 _ 20240108 Entity 변경 이후 변경점에 맞추어 공지사항 등록, 목록 및 상세 조회 API 수정 및 테스트
  src/main/java/com/yanolja_final/domain/notice/dto/request/RegisterNoticeRequest.java
  src/main/java/com/yanolja_final/domain/notice/dto/response/NoticeListResponse.java
  src/main/java/com/yanolja_final/domain/notice/dto/response/NoticeResponse.java
  src/main/java/com/yanolja_final/domain/notice/entity/Notice.java
  src/main/java/com/yanolja_final/domain/notice/exception/NoticeNotFoundException.java
  src/main/java/com/yanolja_final/domain/notice/facade/NoticeFacade.java
  src/main/java/com/yanolja_final/domain/notice/service/NoticeService.java
Labels: 🛠️feature

#106 [Feature] GET /v1/faq/{id} 자주 묻는 질문 상세보기 #73
  src/main/java/com/yanolja_final/domain/faq/controller/FaqController.java
  src/main/java/com/yanolja_final/domain/faq/exception/FaqNotFoundException.java
  src/main/java/com/yanolja_final/domain/faq/facade/FaqFacade.java
  src/main/java/com/yanolja_final/domain/faq/service/FaqService.java
  src/main/java/com/yanolja_final/global/exception/ErrorCode.java
Labels: 🛠️feature

#117 [Feature] DTO Validation 실패 시 어떤 정보가 잘못됐는지 메시지 더 자세히 출력
  src/main/java/com/yanolja_final/global/exception/GlobalExceptionRestAdvice.java
Labels: 🛠️feature

#119 [Feature] GET /v1/advertisements/{id} 광고구좌 조회
  src/main/java/com/yanolja_final/domain/advertisement/controller/AdvertisementController.java
  src/main/java/com/yanolja_final/domain/advertisement/dto/response/AdDetailResponse.java
  src/main/java/com/yanolja_final/domain/advertisement/dto/response/AdPackageResponse.java
  src/main/java/com/yanolja_final/domain/advertisement/exception/AdvertisementNotFound.java
  src/main/java/com/yanolja_final/domain/advertisement/facade/AdFacade.java
  src/main/java/com/yanolja_final/domain/advertisement/service/AdService.java
  src/main/java/com/yanolja_final/domain/packages/entity/Package.java
  src/main/java/com/yanolja_final/domain/packages/entity/PackageDepartureOption.java
  src/main/java/com/yanolja_final/domain/packages/entity/PackageImage.java
  src/main/java/com/yanolja_final/global/exception/ErrorCode.java
Labels: 🛠️feature

#121 [Feature] PATCH v1/my/info #39 내 정보 수정
  src/main/java/com/yanolja_final/domain/user/controller/MyPageController.java
  src/main/java/com/yanolja_final/domain/user/dto/request/UpdateMyPageRequest.java
  src/main/java/com/yanolja_final/domain/user/dto/response/MyPageResponse.java
  src/main/java/com/yanolja_final/domain/user/entity/User.java
  src/main/java/com/yanolja_final/domain/user/facade/MyPageFacade.java
  src/main/java/com/yanolja_final/domain/user/service/MyPageService.java
Labels: 🛠️feature

#130 [Feature] GET /v1/my/info #113 내 정보 조회
  src/main/java/com/yanolja_final/domain/user/controller/MyPageController.java
  src/main/java/com/yanolja_final/domain/user/facade/MyPageFacade.java
  src/main/java/com/yanolja_final/domain/user/service/MyPageService.java
Labels: 🛠️feature

#133 [refactor] 공지사항 Notice->ResponseDTO 전부 controller 에서만 사용하도록 수정
  src/main/java/com/yanolja_final/domain/notice/controller/NoticeController.java
  src/main/java/com/yanolja_final/domain/notice/dto/request/RegisterNoticeRequest.java
  src/main/java/com/yanolja_final/domain/notice/dto/response/NoticeListResponse.java
  src/main/java/com/yanolja_final/domain/notice/dto/response/NoticeResponse.java
  src/main/java/com/yanolja_final/domain/notice/facade/NoticeFacade.java
  src/main/java/com/yanolja_final/domain/notice/service/NoticeService.java
Labels: 🚧refactoring

#134 [refactor] 자주 묻는 질문 Faq->ResponseDTO 전부 controller 에서만 사용하도록 수정
  src/main/java/com/yanolja_final/domain/faq/controller/FaqController.java
  src/main/java/com/yanolja_final/domain/faq/dto/response/FaqListResponse.java
  src/main/java/com/yanolja_final/domain/faq/dto/response/FaqResponse.java
  src/main/java/com/yanolja_final/domain/faq/facade/FaqFacade.java
  src/main/java/com/yanolja_final/domain/faq/service/FaqService.java
Labels: 🚧refactoring

#126 [feat] GET /v1/packages 패키지 전체 목록 구현
  src/main/java/com/yanolja_final/domain/packages/controller/PackageController.java
  src/main/java/com/yanolja_final/domain/packages/dto/response/PackageListItemResponse.java
  src/main/java/com/yanolja_final/domain/packages/entity/Package.java
  src/main/java/com/yanolja_final/domain/packages/facade/PackageFacade.java
  src/main/java/com/yanolja_final/domain/packages/service/PackageService.java
Labels: 🛠️feature

#135 [feat] GET /v1/packages/{id}/schedules 일정 목록 구현
  src/main/java/com/yanolja_final/domain/packages/controller/PackageController.java
  src/main/java/com/yanolja_final/domain/packages/dto/response/PackageScheduleResponse.java
  src/main/java/com/yanolja_final/domain/packages/facade/PackageFacade.java
  src/main/java/com/yanolja_final/domain/packages/service/PackageService.java
Labels: 🛠️feature

#136 [feat] GET /v1/packages/{id}/available-dates 예약가능한 출발일 구현
  src/main/java/com/yanolja_final/domain/packages/controller/PackageController.java
  src/main/java/com/yanolja_final/domain/packages/dto/response/PackageAvailableDateResponse.java
  src/main/java/com/yanolja_final/domain/packages/entity/PackageDepartureOption.java
  src/main/java/com/yanolja_final/domain/packages/facade/PackageFacade.java
Labels: 🛠️feature

#102 [Feature] 테마 패키지 조회 구현
  src/main/java/com/yanolja_final/domain/packages/repository/PackageRepository.java
  src/main/java/com/yanolja_final/domain/packages/service/PackageService.java
  src/main/java/com/yanolja_final/domain/theme/controller/ThemeController.java
  src/main/java/com/yanolja_final/domain/theme/dto/response/PackageSummary.java
  src/main/java/com/yanolja_final/domain/theme/dto/response/ThemePackageResponse.java
  src/main/java/com/yanolja_final/domain/theme/dto/response/ThemeResponse.java
  src/main/java/com/yanolja_final/domain/theme/exception/ThemeNotFoundException.java
  src/main/java/com/yanolja_final/domain/theme/facade/ThemeFacade.java
  src/main/java/com/yanolja_final/domain/theme/repository/ThemeRepository.java
  src/main/java/com/yanolja_final/domain/theme/service/ThemeService.java
  src/main/java/com/yanolja_final/global/config/security/SecurityConfig.java
  src/main/java/com/yanolja_final/global/exception/ErrorCode.java
Labels: 🛠️feature

#142 [Feature] PUT v1/my/password 비밀번호 수정
  src/main/java/com/yanolja_final/domain/user/controller/MyPageController.java
  src/main/java/com/yanolja_final/domain/user/dto/request/UpdatePasswordRequest.java
  src/main/java/com/yanolja_final/domain/user/entity/User.java
  src/main/java/com/yanolja_final/domain/user/exception/DuplicatedCurrentPasswordException.java
  src/main/java/com/yanolja_final/domain/user/facade/MyPageFacade.java
  src/main/java/com/yanolja_final/domain/user/service/MyPageService.java
  src/main/java/com/yanolja_final/global/exception/ErrorCode.java
Labels: 🛠️feature

#147 [Fix] 프론트 요청으로 찜 기능 수정
  src/main/java/com/yanolja_final/domain/review/facade/ReviewFacade.java
  src/main/java/com/yanolja_final/domain/wish/controller/WishController.java
  src/main/java/com/yanolja_final/domain/wish/dto/response/WishListResponse.java
  src/main/java/com/yanolja_final/domain/wish/facade/WishFacade.java
  src/main/java/com/yanolja_final/domain/wish/repository/WishRepository.java
  src/main/java/com/yanolja_final/domain/wish/service/WishService.java
Labels: 👨🏻‍🔧fix, 🚧refactoring

#107 Feature POST /v1/orders
  src/main/java/com/yanolja_final/domain/order/controller/OrderController.java
  src/main/java/com/yanolja_final/domain/order/controller/request/OrderCreateRequest.java
  src/main/java/com/yanolja_final/domain/order/controller/request/OrderGuestInfoRequest.java
  src/main/java/com/yanolja_final/domain/order/controller/response/OrderCreateResponse.java
  src/main/java/com/yanolja_final/domain/order/controller/response/UserInfoResponse.java
  src/main/java/com/yanolja_final/domain/order/dto/OrderDetailInfoDTO.java
  src/main/java/com/yanolja_final/domain/order/entity/Order.java
  src/main/java/com/yanolja_final/domain/order/exception/MaximumCapacityExceededException.java
  src/main/java/com/yanolja_final/domain/order/facade/OrderFacade.java
  src/main/java/com/yanolja_final/domain/order/repository/OrderRepository.java
  src/main/java/com/yanolja_final/domain/order/service/OrderService.java
  src/main/java/com/yanolja_final/domain/packages/entity/Package.java
  src/main/java/com/yanolja_final/domain/packages/entity/PackageDepartureOption.java
  src/main/java/com/yanolja_final/domain/packages/exception/PackageDateNotFoundException.java
  src/main/java/com/yanolja_final/domain/packages/exception/PackageDepartureOptionNotFoundException.java
  src/main/java/com/yanolja_final/domain/packages/repository/PackageDepartureOptionRepository.java
  src/main/java/com/yanolja_final/domain/packages/service/PackageService.java
  src/main/java/com/yanolja_final/global/exception/ErrorCode.java
Labels: 🛠️feature

#129 [Feature] GET /v1/orders 예약 내역 불러오기
  src/main/java/com/yanolja_final/domain/order/controller/OrderController.java
  src/main/java/com/yanolja_final/domain/order/controller/request/OrderCreateRequest.java
  src/main/java/com/yanolja_final/domain/order/controller/response/OrderPackageResponse.java
  src/main/java/com/yanolja_final/domain/order/controller/response/OrderResponse.java
  src/main/java/com/yanolja_final/domain/order/entity/Order.java
  src/main/java/com/yanolja_final/domain/order/facade/OrderFacade.java
  src/main/java/com/yanolja_final/domain/order/repository/OrderRepository.java
  src/main/java/com/yanolja_final/domain/order/service/OrderService.java
  src/main/java/com/yanolja_final/domain/packages/entity/Package.java
  src/main/java/com/yanolja_final/domain/packages/service/PackageService.java
  src/main/java/com/yanolja_final/domain/review/entity/Review.java
  src/main/java/com/yanolja_final/domain/review/repository/ReviewRepository.java
  src/main/java/com/yanolja_final/domain/review/service/ReviewService.java
  src/main/java/com/yanolja_final/domain/wish/repository/WishRepository.java
  src/main/java/com/yanolja_final/domain/wish/service/WishService.java
  src/main/java/com/yanolja_final/global/exception/ErrorCode.java
Labels: 🛠️feature

#139 [Feature] v1/search/options/hashtags (검색옵션) 해쉬태그 목록 조회 기능 구현
  src/main/java/com/yanolja_final/domain/packages/entity/Continent.java
  src/main/java/com/yanolja_final/domain/packages/entity/Hashtag.java
  src/main/java/com/yanolja_final/domain/packages/entity/Nation.java
  src/main/java/com/yanolja_final/domain/packages/repository/HashtagRepository.java
  src/main/java/com/yanolja_final/domain/search/controller/SearchController.java
  src/main/java/com/yanolja_final/domain/search/controller/response/HashtagResponse.java
  src/main/java/com/yanolja_final/domain/search/entity/SearchDestinationOption.java
  src/main/java/com/yanolja_final/domain/search/facade/SearchFacade.java
Labels: 🛠️feature

#148 [Feature] v1/search/options/destinations (검색옵션) 나라,대륙 목록 조회 기능 구현
  src/main/java/com/yanolja_final/domain/packages/dto/response/ContinentResponse.java
  src/main/java/com/yanolja_final/domain/packages/dto/response/NationResponse.java
  src/main/java/com/yanolja_final/domain/packages/repository/ContinentRepository.java
  src/main/java/com/yanolja_final/domain/packages/repository/NationRepository.java
  src/main/java/com/yanolja_final/domain/search/controller/SearchController.java
  src/main/java/com/yanolja_final/domain/search/controller/response/ContinentNationResponse.java
  src/main/java/com/yanolja_final/domain/search/facade/SearchFacade.java
Labels: 🛠️feature

#149 [Feature] v1/search/hashtags 해시태그 목록 (검색 내림차순 순) 기능 구현 & (검색옵션) 나라,대륙 기능 수정
  src/main/java/com/yanolja_final/domain/packages/repository/HashtagRepository.java
  src/main/java/com/yanolja_final/domain/packages/repository/NationRepository.java
  src/main/java/com/yanolja_final/domain/packages/service/ContinentService.java
  src/main/java/com/yanolja_final/domain/packages/service/HashtagService.java
  src/main/java/com/yanolja_final/domain/packages/service/NationService.java
  src/main/java/com/yanolja_final/domain/search/controller/SearchController.java
  src/main/java/com/yanolja_final/domain/search/controller/response/ContinentNationResponse.java
  src/main/java/com/yanolja_final/domain/search/controller/response/ContinentResponse.java
  src/main/java/com/yanolja_final/domain/search/controller/response/HashTagNamesResponse.java
  src/main/java/com/yanolja_final/domain/search/controller/response/NationResponse.java
  src/main/java/com/yanolja_final/domain/search/facade/SearchFacade.java
Labels: 🛠️feature

#152 [Feature] GET v1/search/count (검색) 옵션을 통해 조회 된 패키지 총 수 구하는 기능 구현
  build.gradle
  src/main/java/com/yanolja_final/domain/packages/repository/PackageQueryRepository.java
  src/main/java/com/yanolja_final/domain/packages/service/PackageService.java
  src/main/java/com/yanolja_final/domain/search/controller/SearchController.java
  src/main/java/com/yanolja_final/domain/search/controller/response/SearchedPackageCountResponse.java
  src/main/java/com/yanolja_final/domain/search/facade/SearchFacade.java
  src/main/java/com/yanolja_final/global/config/QueryDSLConfig.java
Labels: 🛠️feature

#78 [Feature] OAuth2 구글, 카카오 로그인 구현
  .env
  build.gradle
  src/main/java/com/yanolja_final/domain/auth/controller/AuthController.java
  src/main/java/com/yanolja_final/domain/user/entity/User.java
  src/main/java/com/yanolja_final/domain/user/repository/UserRepository.java
  src/main/java/com/yanolja_final/global/config/security/KakaoUserInfo.java
  src/main/java/com/yanolja_final/global/config/security/NaverUserInfo.java
  src/main/java/com/yanolja_final/global/config/security/OAuth2LoginSuccessHandler.java
  src/main/java/com/yanolja_final/global/config/security/OAuth2UserInfo.java
  src/main/java/com/yanolja_final/global/config/security/PrincipalDetails.java
  src/main/java/com/yanolja_final/global/config/security/PrincipalOauth2UserService.java
  src/main/java/com/yanolja_final/global/config/security/SecurityConfig.java
  src/main/resources/application.yml
Labels: 🛠️feature

#153 [Feature] GET v1/hahtag-search 해시태그 keyword로 검색 기능 구현
  src/main/java/com/yanolja_final/domain/packages/controller/HashtagController.java
  src/main/java/com/yanolja_final/domain/packages/entity/Hashtag.java
  src/main/java/com/yanolja_final/domain/packages/facade/HashtagFacade.java
  src/main/java/com/yanolja_final/domain/packages/repository/HashtagRepository.java
  src/main/java/com/yanolja_final/domain/packages/repository/PackageRepository.java
  src/main/java/com/yanolja_final/domain/packages/service/HashtagService.java
  src/main/java/com/yanolja_final/domain/packages/service/PackageService.java
  src/main/java/com/yanolja_final/global/config/security/SecurityConfig.java
Labels: 🛠️feature

#161 [Feature] GET v1/search 검색 기능 구현
  src/main/java/com/yanolja_final/domain/packages/facade/HashtagFacade.java
  src/main/java/com/yanolja_final/domain/packages/repository/HashtagRepository.java
  src/main/java/com/yanolja_final/domain/packages/repository/PackageQueryRepository.java
  src/main/java/com/yanolja_final/domain/packages/service/HashtagService.java
  src/main/java/com/yanolja_final/domain/packages/service/PackageService.java
  src/main/java/com/yanolja_final/domain/search/controller/SearchController.java
  src/main/java/com/yanolja_final/domain/search/facade/SearchFacade.java
Labels: 🛠️feature

#157 [Fix, Refactor] 유사한 패키지 API 성능 효율 개선
  src/main/java/com/yanolja_final/domain/packages/facade/PackageFacade.java
  src/main/java/com/yanolja_final/domain/packages/repository/PackageRepository.java
  src/main/java/com/yanolja_final/domain/packages/service/PackageService.java
Labels: 👨🏻‍🔧fix

#162 [Feature] GET /v1/my/upcoming-package 출발 일이 다가오는 패키지
  src/main/java/com/yanolja_final/domain/order/entity/Order.java
  src/main/java/com/yanolja_final/domain/packages/entity/PackageDepartureOption.java
  src/main/java/com/yanolja_final/domain/packages/exception/PassedDepartureDateException.java
  src/main/java/com/yanolja_final/domain/user/controller/MyPageController.java
  src/main/java/com/yanolja_final/domain/user/dto/response/UpcomingPackageResponse.java
  src/main/java/com/yanolja_final/domain/user/entity/User.java
  src/main/java/com/yanolja_final/domain/user/facade/MyPageFacade.java
  src/main/java/com/yanolja_final/domain/user/service/MyPageService.java
  src/main/java/com/yanolja_final/global/exception/ErrorCode.java
Labels: 👨🏻‍🔧fix, 🛠️feature

#163 [Feature & Fix] 변경 사항 적용 및 버그 수정
  src/main/java/com/yanolja_final/domain/order/controller/response/OrderResponse.java
  src/main/java/com/yanolja_final/domain/packages/repository/PackageQueryRepository.java
  src/main/java/com/yanolja_final/domain/search/controller/SearchController.java
Labels: 👨🏻‍🔧fix, 🛠️feature

#166 [feat & refactor] UpcomingPackage_ 예외 처리 및 응답 수정
  src/main/java/com/yanolja_final/domain/order/entity/Order.java
  src/main/java/com/yanolja_final/domain/packages/exception/PassedDepartureDateException.java
  src/main/java/com/yanolja_final/domain/user/dto/response/UpcomingPackageResponse.java
  src/main/java/com/yanolja_final/domain/user/entity/User.java
  src/main/java/com/yanolja_final/domain/user/exception/PassedPackageDateException.java
  src/main/java/com/yanolja_final/domain/user/facade/MyPageFacade.java
  src/main/java/com/yanolja_final/global/exception/ErrorCode.java
Labels: 🛠️feature, 🚧refactoring

#175 [refactor] 동일 패키지 좋아요 요청 예외 추가
  src/main/java/com/yanolja_final/domain/wish/exception/DuplicateWishException.java
  src/main/java/com/yanolja_final/domain/wish/service/WishService.java
  src/main/java/com/yanolja_final/global/exception/ErrorCode.java
Labels: 🚧refactoring

#176 [Refactor] OAuth2 동일 이메일 가입 요청시 예외처리 추가
  src/main/java/com/yanolja_final/global/config/security/PrincipalOauth2UserService.java
  src/main/java/com/yanolja_final/global/exception/ErrorCode.java
Labels: 🚧refactoring

#185 [fix & Refactor] MyPage의 PATCH(내 정보) 와 PUT(비밀번호) 업데이트 수정
  src/main/java/com/yanolja_final/domain/user/controller/MyPageController.java
  src/main/java/com/yanolja_final/domain/user/dto/request/UpdateMyPageRequest.java
Labels: 👨🏻‍🔧fix, 🚧refactoring

#182 Order 수동 패키지에 따른 변경 사항
  src/main/java/com/yanolja_final/domain/order/controller/request/OrderGuestInfoRequest.java
  src/main/java/com/yanolja_final/domain/order/controller/response/OrderCreateResponse.java
  src/main/java/com/yanolja_final/domain/order/controller/response/UserInfoResponse.java
  src/main/java/com/yanolja_final/domain/order/exception/InvalidCancelFeeAgreementException.java
  src/main/java/com/yanolja_final/domain/order/exception/NoGuestsException.java
  src/main/java/com/yanolja_final/domain/order/facade/OrderFacade.java
  src/main/java/com/yanolja_final/global/exception/ErrorCode.java
Labels: 🛠️feature

#186 [refactor] upcoming-package _Dday 를 기준으로 로직 변경
  src/main/java/com/yanolja_final/domain/order/entity/Order.java
  src/main/java/com/yanolja_final/domain/user/entity/User.java
  src/main/java/com/yanolja_final/domain/user/exception/PassedPackageDateException.java
  src/main/java/com/yanolja_final/global/exception/ErrorCode.java
Labels: 🚧refactoring

#188 [Fix] 예약 내역 isWish/isReviewed 동작 안하는 오류 수정
  src/main/java/com/yanolja_final/domain/order/facade/OrderFacade.java
  src/main/java/com/yanolja_final/domain/review/repository/ReviewRepository.java
  src/main/java/com/yanolja_final/domain/review/service/ReviewService.java
  src/main/java/com/yanolja_final/domain/wish/repository/WishRepository.java
  src/main/java/com/yanolja_final/domain/wish/service/WishService.java
Labels: 👨🏻‍🔧fix
